### ISSUE TITLE
Sqlite db corrupted

### ISSUE THREAD

**Issue by pmaAdvensyn** [Nexific/dart_ftpclient#10] opened 2020-03-31 08:42 UTC
When I transfer a backup db file (Sqlite) to ftp. The file is corrupted.
I tested so with a zip file but archive is corrupted too.

My backup or zip file originals are OK and i tested both transfermode (binary and ascii).

I use flutter on tablet Galaxy Tab A.

cordially

**Comment by virtualmarc** [comment] 2020-04-18 13:56
Duplicate of #7

**Closed as completed** 2020-04-18 13:58 UTC
Labels: bug, duplicate
